/**
 * Curated company name → domain map for company logos (CompanyEnrich).
 * Keys are lowercase base names (before parentheses / commas).
 */
export const COMPANY_DOMAINS: Record<string, string> = {
  accenture: "accenture.com",
  accolite: "accolite.com",
  adobe: "adobe.com",
  aetion: "aetion.com",
  agoda: "agoda.com",
  airbnb: "airbnb.com",
  airtel: "airtel.in",
  airtle: "airtel.in",
  "akuna capital": "akuna.com",
  amazon: "amazon.com",
  amdocs: "amdocs.com",
  "american express": "americanexpress.com",
  apple: "apple.com",
  atlassian: "atlassian.com",
  baidu: "baidu.com",
  bankbazaar: "bankbazaar.com",
  bloomberg: "bloomberg.com",
  browserstack: "browserstack.com",
  bytedance: "bytedance.com",
  "c3.ai": "c3.ai",
  "cadence india": "cadence.com",
  capgemini: "capgemini.com",
  "capital one": "capitalone.com",
  carwale: "carwale.com",
  cisco: "cisco.com",
  citicorp: "citigroup.com",
  citrix: "citrix.com",
  citygroup: "citigroup.com",
  cleartrip: "cleartrip.com",
  cloudera: "cloudera.com",
  codenation: "codenation.org",
  cohesity: "cohesity.com",
  coupang: "coupang.com",
  coursera: "coursera.org",
  "d-e shaw": "deshaw.com",
  "d-e-shaw": "deshaw.com",
  "d.e. shaw": "deshaw.com",
  "de shaw": "deshaw.com",
  "de-shaw": "deshaw.com",
  directi: "directi.com",
  doordash: "doordash.com",
  dropbox: "dropbox.com",
  dunzo: "dunzo.com",
  ebay: "ebay.com",
  "epic systems": "epic.com",
  expedia: "expedia.com",
  facebook: "meta.com",
  facebok: "meta.com",
  faceook: "meta.com",
  factset: "factset.com",
  flipkart: "flipkart.com",
  ge: "ge.com",
  geeksforgeeks: "geeksforgeeks.org",
  godaddy: "godaddy.com",
  "goldman sachs": "goldmansachs.com",
  goldmansachs: "goldmansachs.com",
  google: "google.com",
  greyorange: "greyorange.com",
  grofers: "blinkit.com",
  groupon: "groupon.com",
  hcl: "hcltech.com",
  helix: "helix.com",
  hike: "hike.in",
  hsbc: "hsbc.com",
  "housing.com": "housing.com",
  hulu: "hulu.com",
  hyperverge: "hyperverge.co",
  ibm: "ibm.com",
  indeed: "indeed.com",
  infoedge: "infoedge.com",
  informatica: "informatica.com",
  infosys: "infosys.com",
  intuit: "intuit.com",
  "jane street": "janestreet.com",
  jio: "jio.com",
  knowlarity: "knowlarity.com",
  linkedin: "linkedin.com",
  liveramp: "liveramp.com",
  lyft: "lyft.com",
  makemytrip: "makemytrip.com",
  "maq software": "maqsoftware.com",
  mathworks: "mathworks.com",
  "media.net": "media.net",
  medlife: "medlife.com",
  meesho: "meesho.com",
  meta: "meta.com",
  microsoft: "microsoft.com",
  "morgan stanley": "morganstanley.com",
  "morgan stanely": "morganstanley.com",
  myntra: "myntra.com",
  nagarro: "nagarro.com",
  "national instruments": "ni.com",
  netease: "netease.com",
  netflix: "netflix.com",
  npci: "npci.org.in",
  nutanix: "nutanix.com",
  nvidia: "nvidia.com",
  ola: "olacabs.com",
  "ola cabs": "olacabs.com",
  opera: "opera.com",
  oracle: "oracle.com",
  oyo: "oyorooms.com",
  "oyo rooms": "oyorooms.com",
  palantir: "palantir.com",
  "palantir technologies": "palantir.com",
  paypal: "paypal.com",
  paytm: "paytm.com",
  payu: "payu.in",
  philips: "philips.com",
  phonepe: "phonepe.com",
  phonepay: "phonepe.com",
  pinterest: "pinterest.com",
  qualcomm: "qualcomm.com",
  quora: "quora.com",
  salesforce: "salesforce.com",
  samsung: "samsung.com",
  sap: "sap.com",
  "sap labs": "sap.com",
  saplabs: "sap.com",
  servicenow: "servicenow.com",
  siemens: "siemens.com",
  snapchat: "snapchat.com",
  snapdeal: "snapdeal.com",
  swiggy: "swiggy.com",
  synopsys: "synopsys.com",
  tcs: "tcs.com",
  target: "target.com",
  "target corporation": "target.com",
  tencent: "tencent.com",
  teradata: "teradata.com",
  tiktok: "tiktok.com",
  "times internet": "timesinternet.in",
  tokopedia: "tokopedia.com",
  tripadvisor: "tripadvisor.com",
  twitter: "x.com",
  "two sigma": "twosigma.com",
  uber: "uber.com",
  visa: "visa.com",
  vmware: "vmware.com",
  walmart: "walmart.com",
  "walmart labs": "walmart.com",
  wayfair: "wayfair.com",
  wipro: "wipro.com",
  yahoo: "yahoo.com",
  yatra: "yatra.com",
  yelp: "yelp.com",
  zappos: "zappos.com",
  zoho: "zoho.com",
  zycus: "zycus.com",
}
